### ISSUE TITLE
implement umxDoCdiff

### ISSUE THREAD

**Issue by tbates** [tbates/umx#182]
implement the MZ differences causal model

e.g. De Moor, M. H., Boomsma, D. I., Stubbe, J. H., Willemsen, G., & de Geus, E. J. (2008). Testing causality in the association between regular exercise and symptoms of anxiety and depression. *Archives of General Psychiatry*, **65**, 897-905. doi:10.1001/archpsyc.65.8.897

**Comment by tbates** [comment]
![DiffMZ](https://user-images.githubusercontent.com/736156/147500972-143b12c5-b8f9-4fc5-a51a-d6a13984720c.png)

**Comment by tbates** [comment]
e.g.:
```R
umxDoCdiff(x = "ht", "wt",  data = twinData, sep = "")
```

**Comment by mcneale** [comment]
Two issues remain with this approach.  Number 1 is that power is less than in the structural equation modeling approach, so on these grounds alone, its use should be discouraged.  Number two is that there is no inbuilt test of assumptions, unlike SEM where the model can be compared to a saturated model.  This means that biases that may arise from, e.g., different variances in MZ vs. DZ twins can go undetected and uncorrected.  Causal inference is potentially compromised.  So I strongly recommend adding a built-in test of this assumption.

To repair issue #1, it is possible to weight the analyses by the pair sums.  This goes a good way towards repairing good old Haseman-Elston linkage (see first issue of BG) and does the same thing here.  The reason the ML model-fitting approach does better is because a twin pair difference of 2 formed from a pair that is -1sd and +1sd on a scale has a different likelihood than a pair that has one twin at +1 and the other at +3.  The simplistic regression approach doesn't include the weighting - but perhaps this bit of umx actually does it ?
