### ISSUE TITLE
umxObjectiveFIML to make the common 2-line call into one

### ISSUE THREAD

**Issue by tbates** [tbates/umx#29]
umxObjectiveFIML  would wrap the expectation and fit function (used to work this way in OpenMx 1). It was convenient for many default uses).

instead of
    mxExpectationNormal(covariance, means, dimnames = NA, thresholds = NA, threshnames = dimnames)
    mxFitFunctionML(vector = FALSE)

You would say:

    umxObjectiveFIML(covariance, means, dimnames = NA, thresholds = NA, threshnames = dimnames, vector = FALSE)

Would that be useful, or confusing when making models?

_Might_ do same for other functions
* mxAlgebraObjective 
* mxFIMLObjective
* mxLISRELObjective
* mxRowObjective
* mxRObjective
* mxRAMObjective
* mxMLObjective

**Comment by mcneale** [comment]
It might miss the design intent, which was to have flexible mix and match of expectations and fit functions, so that we didn’t end up with nFitFun * nExpectation different functions.  I do get the desire for simplicity, however.

On Sep 29, 2017, at 1:23 PM, Tim Bates <notifications@github.com<mailto:notifications@github.com>> wrote:


umxObjectiveFIML would wrap the expectation and fit function (used to work this way in OpenMx 1). It was convenient for many default uses).

instead of
mxExpectationNormal(covariance, means, dimnames = NA, thresholds = NA, threshnames = dimnames)
mxFitFunctionML(vector = FALSE)

You would say:

umxObjectiveFIML(covariance, means, dimnames = NA, thresholds = NA, threshnames = dimnames, vector = FALSE)


Would that be useful, or confusing when making models?

Might do same for other functions

  *   mxAlgebraObjective
  *   mxFIMLObjective
  *   mxLISRELObjective
  *   mxRowObjective
  *   mxRObjective
  *   mxRAMObjective
  *   mxMLObjective

**Comment by tbates** [comment]
closed: not much use to `umx` users
