### ISSUE TITLE
formatting for plots output by umx

### ISSUE THREAD

**Issue by tbates** [tbates/umx#32]
This is a typical plot output by umx (`umxACE`)
 It uses the variable name for twin 1 as the variable name, and prints to `digits=` precision

Is it OK as is, or should we, by default

1. Strip the twin identifer where known. so `IQ_T1` --> `IQ`
2. For compactness and ease of reading, strip the "0." So "0.77" --> "77"

![default graph output](https://user-images.githubusercontent.com/736156/31625551-50e3422c-b29e-11e7-9c40-2c966beb8b8e.png)

**Comment by mcneale** [comment]
Stripping zeros ok with me.  How about Variance paths - what happened to them?

**Comment by tbates** [comment]
Did this comment (how about variance paths) mean the unit variance assumed for the latents?

**Comment by mcneale** [comment]
Yes it did.  For mathematical completeness variance paths must be included.  Onyx does not label paths that have value 1.0 - another convention that may pretty things up a bit, but it remains ambiguous and mathematically incomplete.  If a figure MUST have missing values or missing variance paths it should, I think, have _as part of the diagram_ notes that indicate that these shortcuts have been taken with the figure.  It is not, IMO, adequate to put it in the caption because figures and captions may become separated if reused etc.  Reproducibility is, to my mind, more important than avoiding faffing around putting variance paths and values on a figure.  Especially when a computer is doing the legwork for you.

**Comment by tbates** [comment]
Agreed, and easy to fix. I think it snuck in because the 1 is implicit. On the TODO list now.

**Comment by tbates** [comment]
* [x] implemented zero-stripping of path labels
* [ ] add unit variance graphics to latents in twin models

**Comment by tbates** [comment]
will handle variance on latents in twin models (which are all 1 when not drawn) as a separate issue
