### ISSUE TITLE
better start values in umxCP models

### ISSUE THREAD

**Issue by tbates** [tbates/umx#51]
The start values for umxCP models are hard coded at values (`0.7`) unlikely to be Kosher for a wide set of inputs: they were just chosen to not die on the runway. (old code below)

`umx 3.0` code should be smarter. Any thoughts on choosing good starts for the different free elements of the model?

```
# Latent common factor
if(correlatedA){
	a_cp_matrix = umxMatrix("a_cp", "Lower", nFac, nFac, free = TRUE, values = .7, jiggle = .05) 
} else {
	a_cp_matrix = umxMatrix("a_cp", "Diag", nFac, nFac, free = TRUE, values = .7, jiggle = .05)
}

```

**Comment by mcneale** [comment]
It's tricky with multiple factors and especially when they are oblique.  How about a 64:36 split for residual:factor variance?  So start residuals so they generate 64% of item variance (i.e., .8itemVariance as a loading on residual latent variable), and then start factor loadings so they are sqrt(.36*itemVariance/nFactors).  Also start the factor correlation off-diagonals at zero even in the case that the model is oblique - otherwise factor variance could get big if there are many factors and factor correlations are large.

**Comment by tbates** [comment]
duplicate with #40
