### ISSUE TITLE
Add WLS to twin models

### ISSUE THREAD

**Issue by tbates** [tbates/umx#56]
1. Use the same `type = c("Auto", "FIML", "WLS", ...)` parameter used in `umxRAM`
      * Auto = treat as FIML if raw and ML if cov
1. Remove failed "censored-data" mode
2. Check model has no def vars.
3. Swap data object to `mxDataWLS`.
4. Swap fit function to `mxFitFunctionWLS`.
5. Apply to
  * `umxACE`
  * `umxCP`
  * `umxIP`
4. [] Create tobit mode for censored continuous data

**Comment by tbates** [comment]
Starting with `umxACE`

- [x] Remove non-functional "censored-data" mode
- [ ] Swap fit function to `mxFitFunctionWLS`.
- [ ] Swap data object to `mxDataWLS`.

**Comment by mcneale** [comment]
Cool!  Note that Josh is working WLS into the backend so that it will be faster to compute weight matrices - but possible to re-use precomputed weight matrix for revised models.

Cheers
Mike

Michael C. Neale, Ph.D.
Professor, Virginia Institute for Psychiatric and Behavioral Genetics
Virginia Commonwealth University
Shipping Address: 800 East Leigh St. Suite 1-156, Richmond VA 23219-1534
Mailing Address : Box 980126 Richmond VA 23298-0126
Telephone: (804) 828-3369

On Nov 10, 2018, at 3:03 PM, Tim Bates <notifications@github.com<mailto:notifications@github.com>> wrote:


Starting with umxACE

  *    Remove non-functional "censored-data" mode
  *    Swap fit function to mxFitFunctionWLS.
  *    Swap data object to mxDataWLS.

**Comment by tbates** [comment]
I wondered how moving the weights to the backend and out of mxData would work... Seems to make more sense to create backend code to mike hunter's `mxDataWLS` function.

**Comment by mcneale** [comment]
Why did this fail?   Nothing wrong with the math afaik.

> 2. Remove failed "censored-data" mode

**Comment by tbates** [comment]
It didn't handle SEs correctly, IIRC?

With WLS coming in in the short term, and a medium term goal of working with Hunter to implement it properly, this seemed wise.
