### ISSUE TITLE
umx_make_TwinData: option to deviate rA from .5

### ISSUE THREAD

**Issue by tbates** [tbates/umx#90]
Could add option to deviate rA from .5 pretty easily

_Originally posted by @tbates in https://github.com/tbates/umx/issues/78#issuecomment-507800756_

**Comment by tbates** [comment]
done

**Comment by mcneale** [comment]
Perhaps this could be done for other variance components too?  If rC could be altered from 1 for DZs, then dominance is readily specified.  A further modification would allow a definition variable to read in rG for each pair (a step towards GREML that should return the same estimates but downwardly-biased SEs due to re-use of individuals if pedigrees are bigger than pairs).

For a more complete generalization I guess we could go for a matrix of coefficients with columns for variance components and rows for different types of relative.  Then all that’s needed is a column to flag the particular type of relative pair.
