### ISSUE TITLE
umxCP: support rotation of factor loadings

### ISSUE THREAD

**Issue by tbates** [tbates/umx#98]
With a multi-factor `umxCP` model, users might want to rotate the pattern of loadings (from common factors to manifests) into a simpler structure.

other features that umxCP could benefit from include allowing the common factors themselves to correlate, and allowing the a, (and c, or e) inputs to independent common factors to correlate with each other.

**Comment by tbates** [comment]
doing this in umxCP risks making that function too much of a swiss watch.

In the first instance, I'll create an S3 `umxRotate.MxModelCP()`, which can
1. take a CP model
2. get the loadings
3. rotate these using user's preferred rotation function
4. replace and fix the loadings matrix
5. re-run
6. print info about the resulting factor structure.
7. free the loadings (so that mxCompare isn't confused and thinks is an amazing high df model with great fit :-)
8. return the rotated model

**Comment by mcneale** [comment]
I'm not sure that this is worthwhile.  Since the rotated CP model fits worse to the twin data than the original solution, it seems unlikely to be of great value.  I suppose one could see how well one's favorite factor rotation does in accounting for the cross-twin covariances as well as the within-twin ones.   Mostly I ran the estimate-rotate-fixloadingstonewrotation-refit just to demonstrate that there is information in the cross-twin covariances to distinguish empirically between otherwise equally-fitting factor rotations.

**Comment by tbates** [comment]
Well... that's easy then :-) I was about done, but will remove.

**Comment by mcneale** [comment]
Er, well if it's pretty much done why not keep it?

**Comment by tbates** [comment]
In there now. if you build from github, 
try:

```R
selDVs = c("gff", "fc", "qol", "hap", "sat", "AD") 
m1 = umxCP(selDVs = selDVs, nFac = 2, data = data, tryHard = "yes")
m2 = umxRotate(m1, rotation = "varimax",  tryHard = "yes")
```

**Comment by mcneale** [comment]
Cool, which rotations are possible?

**Comment by tbates** [comment]
Should work with rotations provided in `library("GPArotation")` and `library("psych")`, e.g

**Orthogonal**: "varimax", "quartimax", "bentlerT", "equamax", "varimin", "geominT" and "bifactor"

**Oblique**: "Promax", "promax", "oblimin", "simplimax", "bentlerQ", "geominQ", "biquartimin" and "cluster"

**Comment by tbates** [comment]
added to docs
